#!/bin/bash

# Usage: ./update-all p_angle s_angle aft_up aft_down pm_1 pm_2 pm_3 
#pm_4 sm_1 sm_2 sm_3 sm_4
# Where:
#p_angle and s_angle are port and starboard servo duty cycles
#aft_up and aft_down are aft motor forward and reverse duty cycles
#pm_1, pm_2, pm_3 and pm_4 are port motor control bytes
#sm_1, sm_2, sm_3 and sm_4 are starboard motor control bytes

# Write duty cycles to PWM outputs.

echo $1 > /sys/devices/ocp.2/pwm_test_P9_22.*/duty
echo $2 > /sys/devices/ocp.2/pwm_test_P9_14.*/duty
echo $3 > /sys/devices/ocp.2/pwm_test_P8_19.*/duty
echo $3 > /sys/devices/ocp.2/pwm_test_P9_42.*/duty

# Write motor bytes to the serial port.

for byte in $5 $6 $7 $8
do
#	printf "%x" $byte >> /dev/ttyO1
	echo -ne $byte > /dev/ttyO1
done
sleep 0.1
for byte in $9 $10 $11 $12
do
	echo -ne $byte > /dev/ttyO1
done

echo 1
